codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      kafka:
        target: auto
        threshold: 1%
        flags:
          - kafka

    patch:
      kafka:
        target: 80
        threshold: 1%
        base: auto
        flags:
          - kafka

flags:
  kafka:
    paths:
      - interop-kafka/
    carryforward: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
  show_carryforward_flags: false
